[package]
name = "exonum"
version = "0.3.0"

[badges]
travis-ci = { repository = "exonum/exonum" }

[dependencies]
log = "0.3.8"
byteorder = "1.1.0"
hex = "0.2.0"
bit-vec = "0.4.4"
vec_map = "0.8.0"
rand = "0.3.15"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
toml = "0.4.2"
clap = "2.25.0"
term = "0.4.6"
colored = "1.5.2"
env_logger = "0.4.3"
hyper = "0.10.13"
cookie = "0.10.1"
router = "0.5.1"
iron = "0.5.1"
headers = "0.1.0"
params = "0.6.0"
mount = "0.3.0"
atty = "0.2.2"
bytes = "0.4.0"
futures = "0.1.14"
tokio-core = "0.1.9"
tokio-io = "0.1.2"
tokio-retry = "0.1.0"
tokio-timer = "0.1.2"

exonum_rocksdb = "0.7"
exonum_sodiumoxide = "0.0.14"
exonum_profiler = { path = "../3rdparty/profiler", version = "0.1.2" }
exonum_flamer = { path = "../3rdparty/flamer", version = "0.1.6", optional = true }

[dev-dependencies]
pretty_assertions = "0.4.0"
tempdir = "0.3.5"

[features]
default = []
long_benchmarks = []
flame_profile = ["exonum_profiler/nomock", "exonum_flamer"]
metrics-log = []
