[package]
name = "dapp"
version = "0.1.0"
authors = ["Ilya Oskin <ilya.arcadich@gmail.com>"]

[dependencies]
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
exonum = {version="0.3", path="../exonum"}
